/* generated by scripts/convert.js — do not edit */
window.__DOC_VERSION__="next";
window.__DOC_VERSIONS__=[{"id":"v1.1","label":"v1.1 (latest)","url":"https://outliyr.github.io/outliyr-docs/","isLatest":true},{"id":"v1.0","label":"v1.0","url":"https://outliyr.github.io/outliyr-docs/v1.0/","isLatest":false},{"id":"next","label":"Unreleased","url":"https://outliyr.github.io/outliyr-docs/next/","isLatest":false}];
